- hosts: nagios-doctor 
  user: root
  vars_files:
    - vars/main.yml
  # user: intentionally blank
  roles:
    - { role: create-deploy-user }


# - hosts: all
#   vars_files:
#     - vars/main.yml
#   # user: intentionally blank
#   remote_user: "{{ deploy }}"
#   roles:
#     - { role: ansible-nagios}
